apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-results-app
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-results-app
  template:
    metadata:
      labels:
        app: vote-results-app
    spec:
      containers:
      - name: vote-app
        image: acrthuantest.azurecr.io/vote-app/vote:v1
        ports:
        - containerPort: 5000
      - name: results-app
        image: acrthuantest.azurecr.io/vote-app/results:v1
        ports:
        - containerPort: 5001
