apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  namespace: voting-app
spec:
  selector:
    app: vote-results-app
  ports:
  - name: vote-port
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: results-port
    protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
